# ==========================================================================
# brew'd apps I use on ALL macs
# ==========================================================================

tap "roots/tap"

brew "asciinema"
brew "asciiquarium"
brew "brew-php-switcher"
brew "composer"
brew "doctl"
brew "gh"
brew "git"
brew "grex"
brew "howdoi"
brew "imagemagick"
brew "jdupes"
brew "jpeg"
brew "mackup"
brew "mise"
brew "nnn"
brew "php-cs-fixer"
brew "pianobar"

# my hammerspoon config uses this
brew "switchaudio-osx"

brew "tag"
brew "task"
brew "tasksh"
# brew "tig"
brew "trash"
brew "tree"
brew "trellis-cli"

# my hammerspoon config uses this
brew "switchaudio-osx"

brew "wifi-password"
brew "wtf"

# ==========================================================================
# casks
# ==========================================================================

cask "alfred"
#cask "bettertouchtool"
cask "dash"
cask "firefox"
cask "forklift"
cask "google-chrome"
cask "hammerspoon"
cask "itsycal"
cask "kap"
cask "mailmate"
cask "obsidian"
cask "raindropio"
cask "slack"
#cask "meetingbar"
cask "wezterm@nightly"

mas "PopClip", id: 445189367
mas "LittleIpsum", id: 405772121
mas "PDFScanner", id: 410968114
