#!/usr/bin/env bash

set -e

brew update

# ==============================================================================
# Alfred
# ==============================================================================

brew cask install alfred
echo "License in LastPass Vault"
# echo "Workflows in SpiderOak Hive"




# ==============================================================================
# bettertouchtool
# ==============================================================================

# brew cask install bettertouchtool
# echo "License in SpiderOak Hive"

# ==============================================================================

# brew cask install betwixt

# BitBar: Put anything in the Mac menu bar
brew cask install bitbar
# echo "Sync in SpiderOak Hive"

# brew cask install cloudapp

# Deluge: BitTorrent client
# full socks5+DHT+blocklist support
# brew cask install deluge

# brew cask install discord
brew cask install docker
brew cask install dropbox
# brew cask install firefox
brew cask install firefox-developer-edition
# brew cask install gimp
# brew cask install gitter
# brew cask install google-chrome-beta
brew cask install google-chrome
brew cask install gpg-suite-no-mail
brew cask install hammerspoon

# inkscape requires xquartz
# brew cask install xquartz
# brew cask install inkscape

# IINA: Modern media player for macOS
# brew cask install iina

brew cask install iterm2

brew cask install java




# ==============================================================================
# Kaleidoscope
# ==============================================================================

# brew cask install kaleidoscope
# echo "License in SpiderOak Hive"




# ==============================================================================
# Beyond Compare
# ==============================================================================

brew cask install beyond-compare
echo "License in LastPass Vault"




# ==============================================================================

brew cask install karabiner-elements




# ==============================================================================
# Marked
# ==============================================================================

# brew cask install marked
# echo "License in SpiderOak Hive"




# ==============================================================================

brew cask install ngrok
# brew cask install robo-3t
# brew cask install spideroakone
# brew cask install switchresx
# brew cask install the-unarchiver
brew cask install raindropio




# ==============================================================================
# Music
# ==============================================================================

# brew cask install spotify spotifree
brew cask install spotify
brew cask install mutespotifyads




# ==============================================================================
# nvALT
# ==============================================================================

brew cask install nvalt




# ==============================================================================
# Notion
# ==============================================================================

brew cask install notion




# ==============================================================================
# Transmit
# ==============================================================================

# brew cask install transmit
# echo "License in email"
# echo "Favorites in SpiderOak sync"




# ============================================================================

# ============================================================================
# Virtualization
# ============================================================================

brew cask install vagrant
# brew cask install virtualbox virtualbox-extension-pack
brew cask install virtualbox




# ============================================================================

# brew cask install vnc-viewer




# ============================================================================
# For Funsies
# ============================================================================

brew cask install electric-sheep
brew cask install homebrew/cask-drivers/sonos




# ============================================================================
# Security and Privacy
# ============================================================================

brew cask install lastpass
brew cask install tunnelbear
brew cask install nordvpn
echo "Set up VPN"

# brew cask install tunnelblick
# echo "Set up vpn"




# ============================================================================
# Comms
# ============================================================================

brew cask install mailmate
echo "License in LastPass Vault"
brew cask install franz
brew cask install skype
brew cask install slack




# ============================================================================
# Schedule & Planning
# ============================================================================

brew cask install fantastical




# ============================================================================
# Adobe
# ============================================================================

brew cask install adobe-creative-cloud
brew cask install adobe-acrobat-reader




# ============================================================================
# File Management
# ============================================================================

brew cask install forklift
echo "License in LastPass Vault"

brew cask install default-folder-x
echo "License in LastPass Vault"




# ============================================================================
# Dev
# ============================================================================

brew cask install dash
echo "License in LastPass Vault"

brew cask install sequel-pro
echo "Favorites can be imported"

brew cask install postman
brew cask install mjml




# ============================================================================
# Backups
# ============================================================================

brew cask install arq
echo "License in LastPass Vault"
