#!/usr/bin/env bash

set -e

# mas install Display Menu
# mas install Microsoft Remote Desktop
# mas install Transmit
# mas install Xcode
mas install 405772121 # LittleIpsum
mas install 890031187 # Marked 2

