#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# =============================================================================
# Main
# =============================================================================

__install() {
  composer diagnose
  composer global require "phpmd/phpmd=@stable"
  composer global require "phpunit/phpunit=^9.6"
  composer global require "psy/psysh=@stable"
  composer global require "sebastian/phpcpd=6.0.3"
  composer global require "squizlabs/php_codesniffer=*"
}
__dko_has composer && __install "$@"
